# Generated by Django 5.1.3 on 2024-11-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votoApp', '0001_initial'),
    ]

    operations = [
       
    ]
