# Generated by Django 5.1.3 on 2024-11-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votoApp', '0002_alter_persona_acceso_alter_persona_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='acceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
