# Generated by Django 5.1.3 on 2024-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votoApp', '0003_alter_persona_acceso_alter_persona_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='acceso',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
